// Liste de 100 citations de motivation en français
const citations = [
    { text: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
    { text: "Le succès est de se coucher chaque soir avec l'âme en paix.", author: "Paulo Coelho" },
    { text: "La seule limite à notre épanouissement de demain sera nos doutes d'aujourd'hui.", author: "Franklin D. Roosevelt" },
    { text: "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute.", author: "Confucius" },
    { text: "Il n'y a qu'une façon d'échouer, c'est d'abandonner avant d'avoir réussi.", author: "Georges Clemenceau" },
    { text: "Croyez en vos rêves et ils se réaliseront peut-être. Croyez en vous et ils se réaliseront sûrement.", author: "Martin Luther King" },
    { text: "Les obstacles sont ces choses effrayantes que vous apercevez lorsque vous quittez votre objectif des yeux.", author: "Henry Ford" },
    { text: "Il n'est pas de vent favorable pour celui qui ne sait pas où il va.", author: "Sénèque" },
    { text: "Vous ne pouvez traverser la mer simplement en restant debout et en regardant l’eau.", author: "Rabindranath Tagore" },
    { text: "Le courage n'est pas l'absence de peur, mais la capacité de vaincre ce qui fait peur.", author: "Nelson Mandela" },
    { text: "Faites de votre vie un rêve, et d'un rêve, une réalité.", author: "Antoine de Saint-Exupéry" },
    { text: "La plus grande erreur que vous puissiez faire dans la vie est d’avoir peur de faire des erreurs.", author: "John C. Maxwell" },
    { text: "Il faut viser la lune, car même en cas d'échec, on atterrit dans les étoiles.", author: "Oscar Wilde" },
    { text: "Ce n'est pas le vent qui décide de la direction, c'est nous-mêmes.", author: "Jim Rohn" },
    { text: "Rien n'est impossible, seuls les limites de nos esprits définissent certaines choses comme inconcevables.", author: "Marc Levy" },
    { text: "Le succès, c'est se promener d'échec en échec tout en restant motivé.", author: "Winston Churchill" },
    { text: "N'attendez pas que les événements arrivent comme vous le souhaitez. Décidez de vouloir ce qui arrive et vous serez heureux.", author: "Épictète" },
    { text: "Les gagnants trouvent des moyens, les perdants des excuses.", author: "F. D. Roosevelt" },
    { text: "La vie commence à la fin de votre zone de confort.", author: "Neale Donald Walsch" },
    { text: "Si vous voulez quelque chose que vous n'avez jamais eu, vous devez faire quelque chose que vous n'avez jamais fait.", author: "Thomas Jefferson" },
    { text: "Votre avenir est créé par ce que vous faites aujourd'hui, pas demain.", author: "Robert T. Kiyosaki" },
    { text: "Les seules limites à nos réalisations de demain sont nos doutes d'aujourd'hui.", author: "Franklin D. Roosevelt" },
    { text: "L'échec est simplement l'opportunité de recommencer, cette fois de manière plus intelligente.", author: "Henry Ford" },
    { text: "Les portes de l'avenir sont ouvertes à ceux qui savent les pousser.", author: "Coluche" },
    { text: "Si vous pouvez le rêver, vous pouvez le faire.", author: "Walt Disney" },
    { text: "Il faut toujours viser la perfection, car elle est atteignable.", author: "Emile Zola" },
    { text: "N'abandonnez jamais. Les grandes choses prennent du temps.", author: "Proverbe" },
    { text: "Les seules personnes qui réussissent sont celles qui cherchent constamment des moyens pour atteindre leurs objectifs.", author: "Charles Chaplin" },
    { text: "La différence entre le possible et l’impossible, c’est la volonté.", author: "Muhammad Ali" },
    { text: "Ne laisse jamais la peur de l'échec t'empêcher de jouer.", author: "Babe Ruth" },
    { text: "L'avenir appartient à ceux qui croient à la beauté de leurs rêves.", author: "Eleanor Roosevelt" },
    { text: "Peu importe à quelle vitesse vous allez, l'important est de ne jamais s'arrêter.", author: "Confucius" },
    { text: "La motivation vous sert de départ. L'habitude vous fait continuer.", author: "Jim Ryun" },
    { text: "Quand vous traversez l’enfer, continuez d’avancer.", author: "Winston Churchill" },
    { text: "Transformez chaque mur en une porte.", author: "Coco Chanel" },
    { text: "Le succès c'est de faire ce que vous aimez, de la manière que vous aimez.", author: "Maya Angelou" },
    { text: "Il n'y a pas d'ascenseur vers le succès. Vous devez prendre les escaliers.", author: "Zig Ziglar" },
    { text: "La discipline est le pont entre les objectifs et les réalisations.", author: "Jim Rohn" },
    { text: "Le succès est la somme de petits efforts, répétés jour après jour.", author: "Robert Collier" },
    { text: "Chaque jour est une nouvelle opportunité de changer votre vie.", author: "Unknown" },
    { text: "Le seul moyen de faire du bon travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
    { text: "Tout commence par un rêve.", author: "Unknown" },
    { text: "La seule chose que vous êtes sûr de ne pas réussir est celle que vous ne tentez pas.", author: "Paul-Emile Victor" },
    { text: "La confiance en soi est le premier secret du succès.", author: "Ralph Waldo Emerson" },
    { text: "Le succès, c’est obtenir ce que vous voulez. Le bonheur, c’est aimer ce que vous obtenez.", author: "Dale Carnegie" },
    { text: "Les idées sont faciles, l’exécution est difficile.", author: "Guy Kawasaki" },
    { text: "Vous n'êtes jamais trop vieux pour vous fixer de nouveaux objectifs ou rêver d'un nouveau rêve.", author: "C.S. Lewis" },
    { text: "Le plus grand échec est de ne pas essayer.", author: "George Clooney" },
    { text: "La vie est trop courte pour la passer à regretter tout ce que vous n'avez pas eu le courage de tenter.", author: "Louis E. Boone" },
    { text: "Visez toujours la lune. Même si vous échouez, vous atterrirez parmi les étoiles.", author: "Les Brown" },
    { text: "Il est toujours trop tôt pour abandonner.", author: "Norman Vincent Peale" },
    { text: "Le succès est d'aller d'échec en échec sans perdre son enthousiasme.", author: "Winston Churchill" },
    { text: "Ce qui nous empêche de réaliser nos rêves, c'est la peur de l'échec.", author: "Paulo Coelho" }
];

// Fonction pour générer une citation aléatoire
function genererCitation() {
    const citationAleatoire = citations[Math.floor(Math.random() * citations.length)];
    document.getElementById("quoteDisplay").innerText = `"${citationAleatoire.text}" - ${citationAleatoire.author}`;
}
